version: '2'
services:
    rabbitmq:
        image: rabbitmq:3.7.4
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - collector-network
    mariadb:
        image: mariadb
        ports:
            - 3306:3306
        restart: always
        volumes:
            - ./script/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
            - ./data/mariadb-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: passpass
            MARIADB_DATABASE: upsellx
        networks:
            - collector-network
    mongo_db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - ./script/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - ./data/mongo-data:/data/db
        environment:
            MONGO_INITDB_DATABASE: upsellx
        networks:
            - collector-network
    service-report:
        build: ./service-report
        image: service-report-image
        environment:
            APP_NAME: report
        tty: true
        ports:
            - '3001:3000'
        depends_on:
            - "mariadb"
        networks:
            - collector-network
    service-collector:
        build: ./service-collector
        image: service-collector-image
        environment:
            APP_NAME: collector
        tty: true
        ports:
            - '3003:3000'
        depends_on:
            - "mariadb"
            - "mongo_db"
            - "rabbitmq"
        networks:
            - collector-network
    app:
        build: ./client-app
        image: client-app
        ports:
            - 3000:80
        environment:
            APP_NAME: client-app
        networks:
            - collector-network
    service-etl:
        build: ./service-etl
        image: service-etl-image
        environment:
            APP_NAME: etl
        ports:
            - '3002:3000'
            - '8081:8081'
        depends_on:
            - "mariadb"
            - "mongo_db"
            - "rabbitmq"
        networks:
            - collector-network
networks:
    collector-network:
        driver: bridge
